name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies (if needed)
        run: pip install -r requirements.txt  # Optional
      - name: Run script
        env:
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          PYTHONUNBUFFERED: 1
        run: python book_ticket.py
